### ISSUE TITLE
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property

### ISSUE THREAD

**Issue by gordana16** [failsafe-engineering/serverless-aws-apigateway-documentation#4]
I get the following deprecation warning when running serverless:

Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
- ServerlessAWSDocumentation for "outputFileName", "extensions"
Please report this issue in plugin issue tracker.
Starting with next major release, this will be communicated with a thrown error.
More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA

**Comment by ottopecz** [comment]
Fixed with v1.1.3. Thanks for the warning.
