### ISSUE TITLE
Add support to download documentation in OpenAPI 3.0

### ISSUE THREAD

**Issue by rovellipaolo** [failsafe-engineering/serverless-aws-apigateway-documentation#40]
The `serverless downloadDocumentation` command currently supports to download the documentation only in OpenAPI 2.0 (Swagger).
It would be nice to support to (optionally) download the documentation also in OpenAPI 3.0.

See also:
 * https://docs.aws.amazon.com/cli/latest/reference/apigateway/get-export.html
 * https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html

**Comment by ottopecz** [comment]
Resolved with v1.2.0
